language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: 'somejavadev-github'
    token:
        secure: "DOv3bE3K2u5uQNmjji5sxOBGYKQeZQlVeHyFkISYmAVd8FyVGyWJxGTqYRQY3Cc6+aDT2jAtaNCdr+xTZ4zm51tsjfbxxyuRB3d8g2umnz55WMqE3/HGmXfE7PUe38Yhmq4G+85qYpQ2tQD60owEoCTK3XyJQfoSL6KWaqimJo0sq+GPLtnun9GtQcwQcYAPHs1A5JI0DklzhvADxwfTd9hGaH2GUxlvgZai6rvRbQDVspCXKog+o68Dtvaa3qG1PA2fnLiA8BUQSsEmeyTPNy5gOl1OV9tO5t/Vf1H3AD2jyVCfXvv0hLit3EJycVuHxhY4bK9StgBSblpnXKV/kPeyYu8Fzhcm2qvhkc83AfeaScKM9LHN+9mGg+ZABdYsX1uElRxPMaoSYTUupjxbMeYjeEheMFgxx0K5toEiw0AVCfTFaJlA0yUzTCxj0+bIhveN+CbaLZi73N11ib/NZvubK4PZhy2UfZqxCP7RHtaqMC0BXemYC5i5XMAxap6mFHfU5UX/Nat5pzNRBMd97xcVQ96mcptTTH8axER+p1QXyHsXnMSMEfDCy7VqGi7Xp5+ej1wuiqHMktmqSfizN3sKhHosNGLq5pLZQt3p1TRx+fh/GcHFt4YsfPdWxAu8X8aWe5AhTh5xCotv9/0QYWs/QH/V2hdWTUTX8KKftS0="
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
