language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: 'somejavadev-github'
    token:
        secure: "LoKRc4w9qxX8JAD4jkeA45ItpUQQP/1uW4ZaynatgoQqkbOAYoBamoLdu7HqV6wWgimta0zGbGdpfOL08E5SMiKQaUQcrMSUwY3iCMulcoMUvSan359nU6TRhfN2UQLC0aGx5cdEKSgC+9JeeCbR4HO8uc7Ahr9yfQY7FvAnxSgfJ3V5+88fyY1+rsMd4zpJL8YH+ujSlUetCMTCOWgtmZlQCHwO9jXENhHAY/N+4CuofUPYssBOlS8eHQQTwsnUNv056YahgbSX47PSP6fObiSuzpjoBbZXqPCvAGXMGyw5LfqcKq/27mMGpdHTqU4wY4Ff6HFRemCScweFT+7BQ4ajAFjM4o4I5pHghGVMg8F0HP3oKXYYY84k0AV0GJ+LA/xyWElr3yD4y8jynRov1ltstkV7sDC6CYVmNg0QMWn+Y8Dpu6gZRMY5lUFpJt15oqZAxlv3JCIYQG5B7mLAj8ByR/KGGX2VnlmzNJ4GH2JZ2WcdBz0SQrjyoiSemIP1Pdhbcim9nOC7UfDNWOkQMrjmuTSitlAhl5nUlS2ApwVR/pQlvexrk07/jhvD/wKqmnrvsb6GxgYuLAGtm9qA6MO5njvLwKs+5z+qcwD5cu9Yq6rmdsdJlT3TYDvQwGcmms4MtI6jWoAh70yzvOdn50FUwnQNtxQEhqIN984O2ZE="
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
